name: Continuous Integration

on:
  push:
    branches:
    - master

  pull_request:
    branches:
    - master

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-python@v2
      if: false
      with: { python-version: "3.8" }

    - name: Install codespell
      if: false
      run: pip3 install codespell

    - name: Lint
      if: false
      run: cmake -D FORMAT_COMMAND=clang-format-12 -P cmake/lint.cmake

    - name: Spell check
      if: false
      run: cmake -P cmake/spell.cmake

  #sanitize:
    #needs: [lint]

    #runs-on: ubuntu-latest

    #steps:
    #- uses: actions/checkout@v2

    # - name: Configure
    #   env: { CXX: clang++-12 }
    #   run: cmake --preset=ci-sanitize

    # - name: Build
    #   run: cmake --build build/sanitize -j 2

    # - name: Test
    #   working-directory: build/sanitize
    #   env:
    #     ASAN_OPTIONS: "strict_string_checks=1:\
    #       detect_stack_use_after_return=1:\
    #       check_initialization_order=1:\
    #       strict_init_order=1:\
    #       detect_leaks=1"
    #     UBSAN_OPTIONS: print_stacktrace=1
    #   run: ctest --output-on-failure -j 2

  benchmark-ubuntu-latest:
    needs: [lint]

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install static analyzers
      run: sudo apt-get install clang-tidy -y -q

    - name: Configure
      shell: pwsh
      run: cmake "--preset=ci-ubuntu"

    - name: Build
      run: cmake --build build --config Release -j 2

      
    - name: Run Benchmark
      working-directory: build
      run: |
        echo "# Benchmark Results (ubuntu-latest)" > ubuntu_benchmark.md
        echo "" >> ubuntu_benchmark.md
        echo "Generated on: $(date '+%Y-%m-%d %H:%M:%S')" >> ubuntu_benchmark.md

        echo ## System Info >> ubuntu_benchmark.md
        echo CPU: $(lscpu | grep "Model name" | sed -e 's/Model name: *//') >> ubuntu_benchmark.md
        echo OS: $(lsb_release -d | sed -e 's/Description: *//') >> ubuntu_benchmark.md
        echo OS Version: $(lsb_release -r | sed -e 's/Release: *//') >> ubuntu_benchmark.md
        echo "" >> ubuntu_benchmark.md
        
        echo "## SSE 4.2" >> ubuntu_benchmark.md
        ./vectormathbench_sse42
        cat benchmark_results.txt >> ubuntu_benchmark.md
        echo "" >> ubuntu_benchmark.md
        
        echo "## AVX" >> ubuntu_benchmark.md
        ./vectormathbench_avx
        cat benchmark_results.txt >> ubuntu_benchmark.md
        echo "" >> ubuntu_benchmark.md
        
        echo "## AVX2" >> ubuntu_benchmark.md
        ./vectormathbench_avx2
        cat benchmark_results.txt >> ubuntu_benchmark.md


    - name: Upload Ubuntu Benchmark
      uses: actions/upload-artifact@v4
      with:
        name: ubuntu_benchmark.md
        path: build/ubuntu_benchmark.md

  benchmark-windows:
    needs: [lint]

    runs-on: windows-2022
    
    steps:
    - uses: actions/checkout@v2
      
    - name: Configure
      shell: pwsh
      run: cmake "--preset=ci-windows"

    - name: Build
      run: cmake --build build --config Release -j 2

    - name: Run Benchmark
      shell: cmd
      working-directory: build/Release
      run: |
          setlocal enabledelayedexpansion
          set OS_NAME=
          set OS_VERSION=
          set CPU_NAME=
          
          REM Capture OS Name
          for /f "tokens=2*" %%i in ('systeminfo ^| findstr /B /C:"OS Name"') do (
              set OS_NAME=%%j
          )
          
          REM Capture OS Version
          for /f "tokens=2*" %%i in ('systeminfo ^| findstr /B /C:"OS Version"') do (
              set OS_VERSION=%%j
          )
          
          REM Capture CPU Name
          for /f "tokens=2 delims==" %%i in ('wmic cpu get name /value') do (
              set CPU_NAME=%%i
          )
          
          echo # Benchmark Results (windows-2022) > windows_benchmark.md
          echo Full Path: %cd%\windows_benchmark.md
          echo. >> windows_benchmark.md
          echo # Benchmark Results (windows-2022) > windows_accuracy.md
          echo Full Path: %cd%\windows_accuracy.md
          echo. >> windows_accuracy.md

          echo Generated on: %date% at %time% >> windows_benchmark.md
          echo. >> windows_benchmark.md
          echo Generated on: %date% at %time% >> windows_accuracy.md
          echo. >> windows_accuracy.md
          
          echo ## System Info >> windows_benchmark.md
          echo CPU: !CPU_NAME! >> windows_benchmark.md
          echo OS: !OS_NAME! >> windows_benchmark.md
          echo OS Version: !OS_VERSION! >> windows_benchmark.md
          echo. >> windows_benchmark.md

          echo ## System Info >> windows_accuracy.md
          echo CPU: !CPU_NAME! >> windows_accuracy.md
          echo OS: !OS_NAME! >> windows_accuracy.md
          echo OS Version: !OS_VERSION! >> windows_accuracy.md
          echo. >> windows_accuracy.md
          
          echo ## SSE 4.2 >> windows_benchmark.md
          vectormathbench_sse42.exe
          type benchmark_results.txt >> windows_benchmark.md
          
          echo. >> windows_benchmark.md
          echo ## AVX >> windows_benchmark.md
          vectormathbench_avx.exe 
          type benchmark_results.txt >> windows_benchmark.md
          
          echo. >> windows_benchmark.md
          echo ## AVX2 >> windows_benchmark.md
          vectormathbench_avx2.exe
          type benchmark_results.txt >> windows_benchmark.md


    - name: Upload Windows Benchmark
      uses: actions/upload-artifact@v4
      with:
        name: windows_benchmark.md
        path: build/Release/windows_benchmark.md

    - name: Upload Windows Accuracy
      uses: actions/upload-artifact@v4
      with:
        name: windows_accuracy.md
        path: build/Release/windows_accuracy.md


  commit-push-benchmark:
    name: Benchmark Update
    needs: [benchmark-windows, benchmark-ubuntu-latest]
    runs-on: ubuntu-latest
  
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        
      - name: Download Windows msvc Output
        uses: actions/download-artifact@v4
        with:
          name: windows_benchmark.md
          
      - name: Download Windows msvc accuracy
        uses: actions/download-artifact@v4
        with:
          name: windows_accuracy.md

      - name: Download Ubuntu Output
        uses: actions/download-artifact@v4
        with:
          name: ubuntu_benchmark.md

      - name: push and commit
        shell: bash
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add windows_benchmark.md
          git add ubuntu_benchmark.md
          git add windows_accuracy.md
          git diff --staged --quiet || (git commit -m "Update benchmark results [auto]" && git push https://${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git HEAD:master)

# i think the issue lies with my cmake setup, i'll have to test it on my ubuntu machine later. until its fixed, only windows is benchmarked

  # docs:
  #   # Deploy docs only when builds succeed
  #   needs: [sanitize]

  #   runs-on: ubuntu-latest

  #   # To enable, first you have to create an orphaned gh-pages branch:
  #   #
  #   #    git switch --orphan gh-pages
  #   #    git commit --allow-empty -m "Initial commit"
  #   #    git push -u origin gh-pages
  #   #
  #   # Edit the RasterDuck placeholder below to your GitHub name, so this action
  #   # runs only in your repository and no one else's fork. After these, delete
  #   # this comment and the last line in the conditional below.
  #   # If you do not wish to use GitHub Pages for deploying documentation, then
  #   # simply delete this job similarly to the coverage one.
  #   if: github.ref == 'refs/heads/master'
  #     && github.event_name == 'push'
  #     && github.repository_owner == 'RasterDuck'
  #     && false

  #   steps:
  #   - uses: actions/checkout@v2

  #   - uses: actions/setup-python@v2
  #     with: { python-version: "3.8" }

  #   - name: Install m.css dependencies
  #     run: pip3 install jinja2 Pygments

  #   - name: Install Doxygen
  #     run: sudo apt-get update -q
  #       && sudo apt-get install doxygen -q -y

  #   - name: Build docs
  #     run: cmake "-DPROJECT_SOURCE_DIR=$PWD" "-DPROJECT_BINARY_DIR=$PWD/build"
  #       -P cmake/docs-ci.cmake

  #   - name: Deploy docs
  #     uses: peaceiris/actions-gh-pages@v3
  #     with:
  #       github_token: ${{ secrets.GITHUB_TOKEN }}
  #       publish_dir: build/docs/html
